[package]
name = "exowasm-node"
version = "0.1.0"
authors = ["Denis Kolodin <denis.kolodin@xdev.re>"]

[dependencies]
dotenv = "0.10.1"
exonum = "0.5.1"
iron = "0.6.0"
bodyparser = "0.8.0"
router = "0.6.0"
serde = "1.0"
serde_json = "1.0"
log = "0.4.1"
exowasm-executor = { path = "../executor" }
