[package]
name = "cryptocurrency"
version = "0.1.0"
authors = ["Sergey Pepyakin <s.pepyakin@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
exowasm-std = { path = "../exowasm-std" }
serde = "1"
serde_derive = "1"
serde_cbor = "0.8.2"

[profile.release]
panic = "abort"
lto = true
